### ISSUE TITLE
AddressSanitizer support

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/coroutine2#12]
Can we please add something like `<asan>on` (similar to `<valgrind>on`) which informs AddressSanitizer of the stack changes? It is described here:
https://github.com/google/sanitizers/issues/189#issuecomment-312914329
https://github.com/llvm-mirror/compiler-rt/blob/master/include/sanitizer/common_interface_defs.h#L166

**Comment by vinniefalco** [comment]
Does `BOOST_USE_ASAN` work?

**Comment by olk** [comment]
I think yes, but you need a very up-to-date version of libasan.
It is only applicable to ucontext (don't know if ASAN is supported on windows - especially the __sanitizer_start_switch_fiber etc.). You can not use it for the assembler backend because this code has no access to the fake-stack, stack-bottom etc. - no global pointer as in ucontext backend.

**Comment by vinniefalco** [comment]
That's cool, I just want to get rid of the false positives. I only run ubsan and asan as part of the CI tests on Travis and they make heavy use of Asio coroutines:
https://travis-ci.org/vinniefalco/beast/jobs/260836700#L1417

So I think this will work well, thanks!

**Comment by bog-dan-ro** [comment]
Do you have more info on this matter? E.g. what is the minimum boost, asan & gcc versions?
I tried Debian's testing boost 1.67 and gcc 8 and the false positive is still there...

**Comment by hamparawa** [comment]
I've also experienced issues with GCC as well. Therefore I had to switched to Clang latest only for CI builds.
