### ISSUE TITLE
unable to create not-a-coroutine

### ISSUE THREAD

**Issue by tobias-loew** [boostorg/coroutine2#46]
With Boost.Coroutine it is possible to create a default constructed coroutine-object and get _not-a-coroutine_, which e.g. later can be swapped with a real coroutine. With Boost.Coroutine2 the default constructor is not available, and construction from a nullptr of type control_block* is private.
Is there any specific reason for not allowing default-created coroutines?

**Comment by olk** [comment]
a coroutine must be associated with an execution context (stack + registers)
additionally boost's coroutine are created in pairs (a push- and a pull-coroutine)
a default constructor would not make sense because it can not be associated with an execution context (and can't be later - at least with the current boost.coroutine syntax)

**Comment by tobias-loew** [comment]
Thanks for the clarification.
